import Head from "next/head";
import { HomeNavbar } from "./home";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const [token, setToken] = useState();

  const router = useRouter();

  useEffect(() => {
    setToken(localStorage.getItem("token"));

    if(!token) {
      router.push('/auth/login')
    }

  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="csrf-token" content="{{ csrf_token() }}" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{token && <HomeNavbar />}</main>
    </>
  );
}
